name: search_pixabay_bloc
description: "Search images from Pixabay"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # BloC architecture
  flutter_bloc: ^8.1.3
  # To compare objects
  equatable: ^2.0.5
  # Http requests
  http: ^1.1.2
  # Manage cache for network images
  cached_network_image: ^3.3.0
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # BloC testing
  bloc_test: ^9.1.5
  test: ^1.24.9
  # Mock classes
  mockito: ^5.4.4


flutter:
  uses-material-design: true

  assets:
    - assets/
